// CI for the `flow`, `state` and `dialects` cells of @tomlarkworthy/mermaid-lens — the mermaid
// flowchart and stateDiagram parsers, their mutators, and the uniform interface over both.
//
// The cells are loaded from the module verbatim (CLAUDE.md tip 17): no copy of a parser lives here.
// `flow` and `state` have no dependencies (`dialects` depends only on those two), and the module's
// cross-module `main.define("module …")` registrations are lazy, so nothing unresolvable is forced.
//
//   node --test tests/notebooks/mermaid-lens.test.js
//
// Corpus fixtures come from tools/scratch/mermaid-lens/fixtures.mjs (generated by extract.mjs).

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { importNotebookModule } from '../../tools/notebook-import.ts';
import { FIXTURES, FLOWCHARTS } from '../../tools/scratch/mermaid-lens/fixtures.mjs';

const imported = await importNotebookModule('modules/@tomlarkworthy/mermaid-lens.js');
// `module.value()` observes through a TEMPORARY variable it then deletes, so a cell read this way
// is left unobserved and is recomputed the next time something observes it — `dialects` would then
// close over a different `flow` object than the one read here. A permanent observer per cell pins
// one generation, so `dialects.flow.parse === flow.parseFlow` holds.
for (const name of ['flow', 'state', 'dialects']) imported.module.variable(true).define([name], (x) => x);
const flow = await imported.value('flow');
const state = await imported.value('state');
const dialects = await imported.value('dialects');

const {
  parseFlow, SHAPES, EDGE_OPS, quoteLabel, splitStatements,
  setLabel, setShape, addNode, addEdge, setEdgeLabel,
  removeEdge, removeNode, setStyle, renameNode, setDirection, mutators
} = flow;

// ---------------------------------------------------------------------------
// span invariants

const isSpan = (v) => Array.isArray(v) && v.length === 2 && typeof v[0] === 'number' && typeof v[1] === 'number';

/** Every span is in range and well ordered. */
function checkSpans(parsed, src, trail) {
  const seen = new Set();
  const walk = (v, path) => {
    if (v === null || v === undefined) return;
    if (seen.has(v)) return;
    if (isSpan(v)) {
      assert.ok(v[0] >= 0, `${path}[0] >= 0 ${trail}`);
      assert.ok(v[1] <= src.length, `${path}[1] <= len ${trail}`);
      assert.ok(v[1] >= v[0], `${path} ordered ${trail}`);
      return;
    }
    if (v instanceof Map) { for (const [k, val] of v) walk(val, `${path}.${k}`); return; }
    if (Array.isArray(v)) { seen.add(v); v.forEach((x, i) => walk(x, `${path}[${i}]`)); return; }
    if (typeof v !== 'object') return;
    seen.add(v);
    for (const k of Object.keys(v)) walk(v[k], `${path}.${k}`);
  };
  walk({ h: parsed.header, n: parsed.nodes, e: parsed.edges, s: parsed.styles, g: parsed.subgraphs, t: parsed.statements, x: parsed.errors }, '');
}

/** Every recorded text field equals the slice of its own span. */
function checkRoundTrip(parsed, src, trail) {
  const eq = (span, text, what) => assert.equal(src.slice(span[0], span[1]), text, `${what} ${trail}`);
  for (const n of parsed.nodes.values()) {
    for (const s of n.idSpans) eq(s, n.id, `node id ${n.id}`);
    if (n.decl) {
      eq(n.decl.labelSpan, n.decl.label, `decl label ${n.id}`);
      eq(n.decl.openSpan, n.decl.open, `decl open ${n.id}`);
      eq(n.decl.closeSpan, n.decl.close, `decl close ${n.id}`);
      assert.ok(SHAPES[n.decl.shape], `shape table has ${n.decl.shape}`);
      assert.equal(SHAPES[n.decl.shape].open, n.decl.open);
      assert.equal(SHAPES[n.decl.shape].close, n.decl.close);
    }
    for (const c of n.classes) eq(c.span, c.name, `class ${c.name}`);
  }
  for (const e of parsed.edges) {
    eq(e.fromSpan, e.from, `edge from ${e.from}`);
    eq(e.toSpan, e.to, `edge to ${e.to}`);
    if (e.labelSpan) eq(e.labelSpan, e.label, 'edge label');
    assert.equal(e.span[0], e.opSpan[0]);
    assert.ok(e.span[1] >= e.opSpan[1]);
  }
  for (const s of parsed.styles) {
    eq(s.bodySpan, s.body, 'style body');
    for (const t of s.targets) eq(t.span, t.name, 'style target');
  }
  for (const g of parsed.subgraphs) {
    if (g.titleSpan) eq(g.titleSpan, g.title, 'subgraph title');
    if (g.idSpan) eq(g.idSpan, g.id, 'subgraph id');
  }
  if (parsed.header && parsed.header.dirSpan) {
    assert.equal(src.slice(parsed.header.dirSpan[0], parsed.header.dirSpan[1]).toUpperCase(), parsed.header.dir);
  }
}

/** Parses with zero errors and every span round-trips. */
function ok(src) {
  const p = parseFlow(src);
  assert.deepEqual(p.errors, [], `errors for ${JSON.stringify(src)}`);
  checkSpans(p, src, JSON.stringify(src));
  checkRoundTrip(p, src, JSON.stringify(src));
  return p;
}

/** A mutation result must re-parse cleanly. */
const reparsed = (src) => ok(src);

const edgeKeys = (p) => p.edges.map((e) => `${e.from}>${e.to}`);

// ---------------------------------------------------------------------------

describe('corpus fixtures', () => {
  it('the extraction holds four sources, two of them flowcharts, none with ${} holes', () => {
    assert.equal(FIXTURES.length, 4);
    assert.deepEqual(FIXTURES.filter((f) => f.hasHole).map((f) => f.name), []);
    assert.equal(FLOWCHARTS.length, 2);
  });

  for (const f of FLOWCHARTS) {
    it(`zero errors and full span round-trip: ${f.name}`, () => { ok(f.src); });
  }

  it('non-flowchart sources are rejected, not crashed', () => {
    for (const f of FIXTURES.filter((x) => x.kind === 'not-flowchart')) {
      const p = parseFlow(f.src);
      assert.equal(p.header, null, f.name);
      assert.ok(p.errors.length > 0, f.name);
      checkSpans(p, f.src, f.name);
    }
  });

  it('graph_td_tour: five nodes, decl on the later occurrence, emoji label', () => {
    const p = ok(FLOWCHARTS[0].src);
    assert.equal(p.header.kind, 'graph');
    assert.equal(p.header.dir, 'TD');
    assert.deepEqual([...p.nodes.keys()].sort(), ['A', 'B', 'C', 'D', 'E']);
    assert.equal(p.edges.length, 5);
    const d = p.nodes.get('D');
    assert.equal(d.idSpans.length, 3);
    assert.equal(d.decl.shape, 'rect');
    assert.equal(d.decl.label, 'D 🕣');
    assert.equal(p.nodes.get('A').decl, null);
  });

  it('flowchart_td_robocoop3: stadium decls, quoted mid-labels, `End` is not the keyword', () => {
    const p = ok(FLOWCHARTS[1].src);
    assert.equal(p.header.kind, 'flowchart');
    assert.equal(p.nodes.get('Start').decl.shape, 'stadium');
    assert.equal(p.nodes.get('End').decl.shape, 'stadium');
    assert.equal(p.nodes.get('Type').decl.shape, 'diamond');
    assert.equal(p.nodes.get('Type').decl.label, 'Tool type?');
    assert.deepEqual(p.edges.filter((e) => e.label).map((e) => e.label).sort(),
      ['Lifecycle tool', 'Task tool', 'function_call', 'function_output']);
    assert.equal(p.edges.length, 7);
  });
});

// ---------------------------------------------------------------------------

describe('shapes', () => {
  const CASES = [
    ['A[text]', 'rect'],
    ['A(text)', 'round'],
    ['A([text])', 'stadium'],
    ['A[[text]]', 'subroutine'],
    ['A[(text)]', 'cylinder'],
    ['A((text))', 'circle'],
    ['A>text]', 'asymmetric'],
    ['A{text}', 'diamond'],
    ['A{{text}}', 'hexagon'],
    ['A[/text/]', 'parallelogram'],
    ['A[\\text\\]', 'parallelogram-alt'],
    ['A[/text\\]', 'trapezoid'],
    ['A[\\text/]', 'trapezoid-alt'],
    ['A(((text)))', 'double-circle']
  ];

  it('SHAPES covers every supported shape exactly once', () => {
    assert.deepEqual(Object.keys(SHAPES).sort(), CASES.map((c) => c[1]).sort());
  });

  for (const [frag, shape] of CASES) {
    it(`${shape}: ${frag}`, () => {
      const src = `graph TD\n${frag}\n`;
      const p = ok(src);
      const d = p.nodes.get('A').decl;
      assert.equal(d.shape, shape);
      assert.equal(d.label, 'text');
      // the brackets around labelSpan really are SHAPES[shape]
      assert.equal(src.slice(d.span[0] + 1, d.labelSpan[0]), SHAPES[shape].open);
      assert.equal(src.slice(d.labelSpan[1], d.span[1]), SHAPES[shape].close);
      // and the same fragment declares when it sits on an edge endpoint
      const q = ok(`graph TD\nZ --> ${frag}\n`);
      assert.equal(q.nodes.get('A').decl.shape, shape);
      assert.equal(q.edges.length, 1);
    });
  }

  it('a quoted label keeps its span inside the quotes, and `;` does not split the statement', () => {
    const src = 'graph TD\nA["a;b (c)"] --> B\n';
    const p = ok(src);
    const d = p.nodes.get('A').decl;
    assert.equal(d.label, 'a;b (c)');
    assert.equal(src[d.labelSpan[0] - 1], '"');
    assert.equal(src[d.labelSpan[1]], '"');
    assert.equal(p.edges.length, 1);
  });
});

// ---------------------------------------------------------------------------

describe('edge operators', () => {
  // one entry per link type the parser reports, with that type's spelling variants
  const BY_TYPE = {
    arrow: [['-->', null], ['--x', null], ['---->', null], ['<-->', null], ['-- text -->', 'text']],
    open: [['---', null], ['-------', null], ['-- text ---', 'text']],
    dotted: [['-.->', null], ['-.-', null], ['-. text .->', 'text']],
    thick: [['==>', null], ['===', null], ['== text ==>', 'text']],
    invisible: [['~~~', null]]
  };

  it('EDGE_OPS names every link type the parser reports', () => {
    assert.deepEqual(Object.keys(EDGE_OPS).sort(), Object.keys(BY_TYPE).sort());
  });

  for (const [type, cases] of Object.entries(BY_TYPE)) {
    it(`${type}: ${cases.map((c) => c[0]).join(' ')}`, () => {
      for (const [op, label] of cases) {
        const src = `graph TD\nA ${op} B\n`;
        const p = ok(src);
        assert.equal(p.edges.length, 1, op);
        const e = p.edges[0];
        assert.equal(e.type, type, op);
        assert.equal(e.from, 'A', op);
        assert.equal(e.to, 'B', op);
        assert.equal(e.label, label, op);
        assert.equal(src.slice(e.opSpan[0], e.opSpan[1]), op);
        assert.deepEqual(e.span, e.opSpan, op);
        assert.equal(src.slice(e.statementSpan[0], e.statementSpan[1]), `A ${op} B`);
      }
    });
  }

  it('pipe label: -->|text| widens span past the operator', () => {
    const src = 'graph TD\nA -->|yes| B\n';
    const p = ok(src);
    const e = p.edges[0];
    assert.equal(e.type, 'arrow');
    assert.equal(e.label, 'yes');
    assert.equal(src.slice(e.opSpan[0], e.opSpan[1]), '-->');
    assert.equal(src.slice(e.span[0], e.span[1]), '-->|yes|');
  });
});

// ---------------------------------------------------------------------------

describe('structure', () => {
  it('chain A --> B --> C gives two edges sharing one statement', () => {
    const p = ok('graph TD\nA --> B --> C\n');
    assert.deepEqual(edgeKeys(p), ['A>B', 'B>C']);
    assert.equal(p.edges[0].linkIndex, 0);
    assert.equal(p.edges[1].linkIndex, 1);
    assert.deepEqual(p.edges[0].statementSpan, p.edges[1].statementSpan);
    assert.equal(p.nodes.get('B').idSpans.length, 1);
  });

  it('fan A & B --> C, and a fan on both sides is a cross product', () => {
    assert.deepEqual(edgeKeys(ok('graph TD\nA & B --> C\n')), ['A>C', 'B>C']);
    assert.deepEqual(edgeKeys(ok('graph TD\nA & B --> C & D\n')), ['A>C', 'A>D', 'B>C', 'B>D']);
  });

  it('subgraphs nest, and nodeIds are transitive', () => {
    const src = [
      'flowchart TD',
      '  subgraph outer [Outer box]',
      '    A --> B',
      '    subgraph inner',
      '      C --> D',
      '    end',
      '  end',
      '  B --> C'
    ].join('\n');
    const p = ok(src);
    assert.deepEqual(p.subgraphs.map((g) => g.id), ['outer', 'inner']);
    assert.equal(p.subgraphs[0].title, 'Outer box');
    assert.deepEqual(p.subgraphs[0].nodeIds, ['A', 'B', 'C', 'D']);
    assert.deepEqual(p.subgraphs[1].nodeIds, ['C', 'D']);
    assert.equal(src.slice(p.subgraphs[1].bodySpan[0], p.subgraphs[1].bodySpan[1]).trim(), 'C --> D');
    assert.equal(p.statements.filter((s) => s.kind === 'subgraph').length, 2);
    assert.equal(p.statements.filter((s) => s.kind === 'end').length, 2);
  });

  it('`;`-separated one-liner', () => {
    const src = 'graph TD; A-->B; B-->C';
    const p = ok(src);
    assert.equal(p.header.dir, 'TD');
    assert.deepEqual(edgeKeys(p), ['A>B', 'B>C']);
    assert.deepEqual(p.statements.map((s) => s.kind), ['header', 'edge', 'edge']);
  });

  it('splitStatements ignores separators inside brackets and quotes', () => {
    const src = 'A["a;b\nc"] --> B; C --> D';
    assert.deepEqual(splitStatements(src).map((s) => src.slice(s.span[0], s.span[1])),
      ['A["a;b\nc"] --> B', 'C --> D']);
  });

  it('never throws on junk', () => {
    for (const bad of ['', '   ', 'graph TD\n!!!\n', 'graph TD\nA -->\n', 'graph TD\nA -->|unterminated\n',
                       'graph TD\nend\n', 'graph TD\nsubgraph s\nA-->B\n']) {
      const p = parseFlow(bad);
      assert.ok(Array.isArray(p.errors));
      checkSpans(p, bad, JSON.stringify(bad));
    }
    assert.deepEqual(parseFlow(null).errors, []);
  });
});

// ---------------------------------------------------------------------------

describe('mutators', () => {
  it('setLabel rewrites a decl, adds one where missing, and quotes what needs it', () => {
    assert.equal(setLabel('graph TD\nA[old] --> B\n', 'A', 'new'), 'graph TD\nA[new] --> B\n');
    assert.equal(setLabel('graph TD\nA --> B\n', 'A', 'hello'), 'graph TD\nA[hello] --> B\n');
    assert.equal(setLabel('graph TD\nA{{old}} --> B\n', 'A', 'new'), 'graph TD\nA{{new}} --> B\n');
    assert.equal(quoteLabel('a|b'), '"a|b"');
    const out = setLabel('graph TD\nA --> B\n', 'A', 'a (b) [c] {d} |e|');
    assert.equal(reparsed(out).nodes.get('A').decl.label, 'a (b) [c] {d} |e|');
    assert.throws(() => setLabel('graph TD\nA --> B\n', 'Z', 'x'));
  });

  it('setShape re-brackets to every shape, and invents a decl when there is none', () => {
    for (const name of Object.keys(SHAPES)) {
      const p = reparsed(setShape('graph TD\nA[label] --> B\n', 'A', name));
      assert.equal(p.nodes.get('A').decl.shape, name);
      assert.equal(p.nodes.get('A').decl.label, 'label');
      assert.equal(p.edges.length, 1);
    }
    assert.equal(setShape('graph TD\nA --> B\n', 'A', 'circle'), 'graph TD\nA((A)) --> B\n');
    assert.throws(() => setShape('graph TD\nA --> B\n', 'A', 'trapdoor'));
  });

  it('addEdge appends at the matching indent, honours type and label, stays out of a subgraph', () => {
    assert.equal(addEdge('flowchart TD\n    A --> B\n', 'B', 'C'), 'flowchart TD\n    A --> B\n    B --> C\n');
    for (const type of Object.keys(EDGE_OPS)) {
      const p = reparsed(addEdge('graph TD\nA --> B\n', 'B', 'C', { type }));
      assert.equal(p.edges.at(-1).type, type);
    }
    assert.equal(addEdge('graph TD\nA --> B\n', 'B', 'C', { label: 'why not' }), 'graph TD\nA --> B\nB -->|why not| C\n');
    const out = addEdge('flowchart TD\nsubgraph s\nA --> B\nend\nB --> C\n', 'C', 'D');
    assert.deepEqual(reparsed(out).subgraphs[0].nodeIds, ['A', 'B']);
    assert.ok(out.indexOf('C --> D') > out.indexOf('end'));
    assert.throws(() => addEdge('graph TD\nA-->B\n', 'A B', 'C'));
  });

  it('addNode appends a decl, quotes the label, refuses a duplicate id', () => {
    const out = addNode('flowchart TD\n    A --> B\n', 'C', 'third');
    assert.equal(out, 'flowchart TD\n    A --> B\n    C[third]\n');
    const p = reparsed(out);
    assert.equal(p.nodes.get('C').decl.shape, 'rect');
    assert.equal(p.statements.at(-1).kind, 'node');
    assert.equal(addNode('graph TD\nA --> B\n', 'C', 'a [b] |c|'), 'graph TD\nA --> B\nC["a [b] |c|"]\n');
    assert.equal(addNode('graph TD\nA --> B\n', 'C'), 'graph TD\nA --> B\nC[C]\n');
    assert.throws(() => addNode('graph TD\nA --> B\n', 'A', 'x'), /already exists/);
    assert.throws(() => addNode('graph TD\nA --> B\n', 'not an id', 'x'));
  });

  it('removeEdge on a chain: head, tail and middle each rebuild the statement', () => {
    const drop = (src, pick) => removeEdge(src, parseFlow(src).edges.find(pick));
    assert.equal(drop('graph TD\nA --> B --> C\n', (e) => e.from === 'A'), 'graph TD\nB --> C\n');
    assert.equal(drop('graph TD\nA --> B --> C\n', (e) => e.from === 'B'), 'graph TD\nA --> B\n');
    const mid = drop('graph TD\nA --> B --> C --> D\n', (e) => e.from === 'B');
    assert.equal(mid, 'graph TD\nA --> B\nC --> D\n');
    assert.deepEqual(edgeKeys(reparsed(mid)), ['A>B', 'C>D']);
    // a head that carries a decl keeps it
    const kept = drop('graph TD\nA[keep me] --> B --> C\n', (e) => e.from === 'A');
    assert.equal(reparsed(kept).nodes.get('A').decl.label, 'keep me');
    // lone statement, and a fan member
    assert.equal(drop('graph TD\nA --> B\nC --> D\n', (e) => e.from === 'A'), 'graph TD\nC --> D\n');
    assert.equal(drop('graph TD\nA & B --> C\n', (e) => e.from === 'A'), 'graph TD\nB --> C\n');
  });

  it('removeNode takes the decl, every incident edge and the style line', () => {
    const src = 'graph TD\nA --> B\nB --> C\nB[middle]\nstyle B fill:#f9f\nstyle A fill:#eee\n';
    const out = removeNode(src, 'B');
    assert.equal(out, 'graph TD\nstyle A fill:#eee\n');
    const p = reparsed(out);
    assert.equal(p.nodes.has('B'), false);
    assert.equal(p.edges.length, 0);
    // splits a chain running through the node; unknown id is a no-op
    assert.deepEqual(edgeKeys(reparsed(removeNode('graph TD\nA --> B --> C\nC --> D\n', 'B'))), ['C>D']);
    assert.equal(removeNode('graph TD\nA --> B\n', 'Z'), 'graph TD\nA --> B\n');
  });

  it('setStyle appends, merges over existing keys, and lands outside a subgraph', () => {
    assert.equal(setStyle('graph TD\nA --> B\n', 'A', { fill: '#f9f', stroke: '#333' }),
      'graph TD\nA --> B\nstyle A fill:#f9f,stroke:#333\n');
    const merged = setStyle('graph TD\nA --> B\nstyle A fill:#eee,stroke:#333\n', 'A', { fill: '#f9f', 'stroke-width': '2px' });
    assert.equal(merged, 'graph TD\nA --> B\nstyle A fill:#f9f,stroke:#333,stroke-width:2px\n');
    reparsed(merged);
    const other = reparsed(setStyle('graph TD\nA --> B\nstyle B fill:#eee\n', 'A', { fill: '#f9f' }));
    assert.deepEqual(other.styles.map((s) => `${s.target}=${s.body}`).sort(), ['A=fill:#f9f', 'B=fill:#eee']);
    const outside = setStyle('flowchart TD\nsubgraph s\nA --> B\nend\n', 'A', { fill: '#f9f' });
    assert.ok(outside.indexOf('style A') > outside.indexOf('end'));
  });

  it('renameNode rewrites ids, decls, style targets and subgraph ids only', () => {
    const out = renameNode('graph TD\nA[label] --> B\nB --> A\nstyle A fill:#f9f\nclass A,B warn\n', 'A', 'Alpha');
    assert.equal(out, 'graph TD\nAlpha[label] --> B\nB --> Alpha\nstyle Alpha fill:#f9f\nclass Alpha,B warn\n');
    const p = reparsed(out);
    assert.equal(p.nodes.has('A'), false);
    assert.equal(p.nodes.get('Alpha').idSpans.length, 2);
    // a label that merely contains the id is left alone
    assert.equal(renameNode('graph TD\nA[A is A] --> B\n', 'A', 'Z'), 'graph TD\nZ[A is A] --> B\n');
    const sg = reparsed(renameNode('flowchart TD\nsubgraph box\nA --> B\nend\nbox --> C\n', 'box', 'crate'));
    assert.equal(sg.subgraphs[0].id, 'crate');
    assert.throws(() => renameNode('graph TD\nA-->B\n', 'Z', 'Y'));
    assert.throws(() => renameNode('graph TD\nA-->B\n', 'A', 'not an id'));
  });

  it('setDirection replaces, adds, or prepends a whole header', () => {
    assert.equal(setDirection('graph TD\nA --> B\n', 'LR'), 'graph LR\nA --> B\n');
    assert.equal(setDirection('graph\nA --> B\n', 'BT'), 'graph BT\nA --> B\n');
    assert.equal(setDirection('A --> B\n', 'RL'), 'graph RL\nA --> B\n');
    assert.equal(setDirection('flowchart TD\nA-->B\n', 'LR'), 'flowchart LR\nA-->B\n');
    assert.equal(reparsed(setDirection('graph TD; A-->B', 'LR')).header.dir, 'LR');
    assert.throws(() => setDirection('graph TD\nA-->B\n', 'XY'));
  });

  it('setEdgeLabel adds a |label| to every unlabelled link type', () => {
    const relabel = (src, text) => setEdgeLabel(src, parseFlow(src).edges[0], text);
    for (const [before, after, type] of [
      ['A --> B', 'A -->|hi| B', 'arrow'],
      ['A --- B', 'A ---|hi| B', 'open'],
      ['A -.-> B', 'A -.->|hi| B', 'dotted'],
      ['A ==> B', 'A ==>|hi| B', 'thick'],
      ['A ~~~ B', 'A ~~~|hi| B', 'invisible']
    ]) {
      const out = relabel(`graph TD\n${before}\n`, 'hi');
      assert.equal(out, `graph TD\n${after}\n`);
      const p = reparsed(out);
      assert.equal(p.edges[0].label, 'hi');
      assert.equal(p.edges[0].type, type);
    }
    assert.equal(relabel('graph TD\nA-->B\n', 'hi'), 'graph TD\nA-->|hi|B\n');
  });

  it('setEdgeLabel replaces in place in both the pipe and the mid-link form', () => {
    const relabel = (src, text) => setEdgeLabel(src, parseFlow(src).edges[0], text);
    assert.equal(relabel('graph TD\nA -->|old| B\n', 'new'), 'graph TD\nA -->|new| B\n');
    assert.equal(relabel('graph TD\nA -- old --> B\n', 'new'), 'graph TD\nA -- new --> B\n');
    assert.equal(relabel('graph TD\nA ---->|x| B\n', 'y'), 'graph TD\nA ---->|y| B\n');
    // `;` and `>` cannot live mid-link, so the label moves to the |text| form, quoted
    assert.equal(relabel('graph TD\nA -- old --> B\n', 'a>b'), 'graph TD\nA -->|"a>b"| B\n');
    assert.equal(reparsed(relabel('graph TD\nA --> B\n', 'a;b')).edges[0].label, 'a;b');
    // targets the right link of a chain
    const src = 'graph TD\nA --> B --> C\n';
    assert.equal(setEdgeLabel(src, parseFlow(src).edges[1], 'second'), 'graph TD\nA --> B -->|second| C\n');
    assert.throws(() => relabel('graph TD\nA --> B\n', 'a|b'), /cannot contain `\|`/);
    assert.throws(() => setEdgeLabel('graph TD\nXX --> YY\n', parseFlow('graph TD\nA --> B\n').edges[0], 'x'), /stale/);
  });

  it('setEdgeLabel clears a label in both forms, collapsing a mid-link operator', () => {
    const relabel = (src) => setEdgeLabel(src, parseFlow(src).edges[0], '');
    assert.equal(relabel('graph TD\nA -->|old| B\n'), 'graph TD\nA --> B\n');
    assert.equal(relabel('graph TD\nA ---->|x| B\n'), 'graph TD\nA ----> B\n');
    for (const [before, after] of [
      ['A -- old --> B', 'A --> B'],
      ['A -- old --- B', 'A --- B'],
      ['A -. old .-> B', 'A -.-> B'],
      ['A == old ==> B', 'A ==> B'],
      ['A <-- old --> B', 'A <--> B']
    ]) {
      const out = relabel(`graph TD\n${before}\n`);
      assert.equal(out, `graph TD\n${after}\n`);
      assert.equal(reparsed(out).edges[0].label, null);
    }
    // documented loss: a mid-link clear normalises a long dash run
    assert.equal(relabel('graph TD\nA -- old ----> B\n'), 'graph TD\nA --> B\n');
    // clearing an already-unlabelled edge is a no-op
    assert.equal(relabel('graph TD\nA --> B\n'), 'graph TD\nA --> B\n');
  });

  it('the mutators registry lists every rewriting helper and nothing else', () => {
    assert.deepEqual(Object.keys(mutators).sort(), [
      'addEdge', 'addNode', 'addSubgraph', 'moveNode', 'removeEdge', 'removeNode', 'removeSubgraph', 'renameNode',
      'setClassDef', 'setClick', 'setDirection', 'setEdgeLabel', 'setEdgeType', 'setLabel', 'setLinkStyle', 'setNodeClass',
      'setShape', 'setStyle', 'setSubgraphDirection', 'setSubgraphTitle'
    ]);
    for (const name of Object.keys(mutators)) {
      assert.equal(typeof mutators[name], 'function', name);
      assert.equal(mutators[name].name, name, name);
    }
    assert.equal(mutators.addNode, addNode);
    assert.equal(mutators.setEdgeLabel, setEdgeLabel);
  });
});

// ---------------------------------------------------------------------------

describe('mutations on the real fixtures', () => {
  for (const f of FLOWCHARTS) {
    it(`a round of edits stays parseable: ${f.name}`, () => {
      const first = [...parseFlow(f.src).nodes.keys()][0];
      let s = f.src;
      s = setLabel(s, first, 'renamed [x]');
      reparsed(s);
      s = setShape(s, first, 'hexagon');
      assert.equal(reparsed(s).nodes.get(first).decl.shape, 'hexagon');
      s = setStyle(s, first, { fill: '#f9f' });
      s = addNode(s, 'EXTRA', 'an extra node');
      assert.equal(reparsed(s).nodes.get('EXTRA').decl.label, 'an extra node');
      s = setEdgeLabel(s, parseFlow(s).edges[0], 'tagged');
      assert.equal(reparsed(s).edges[0].label, 'tagged');
      s = setEdgeLabel(s, parseFlow(s).edges[0], '');
      assert.equal(reparsed(s).edges[0].label, null);
      s = removeNode(s, 'EXTRA');
      s = addEdge(s, first, 'NEWNODE', { label: 'added' });
      assert.ok(reparsed(s).edges.some((e) => e.to === 'NEWNODE' && e.label === 'added'));
      s = renameNode(s, 'NEWNODE', 'Renamed');
      assert.ok(reparsed(s).nodes.has('Renamed'));
      s = removeNode(s, 'Renamed');
      assert.equal(reparsed(s).nodes.has('Renamed'), false);
      s = setDirection(s, 'LR');
      assert.equal(reparsed(s).header.dir, 'LR');
    });

    it(`every edge can be removed one at a time: ${f.name}`, () => {
      let s = f.src;
      for (let guard = 0; guard < 50; guard++) {
        const p = parseFlow(s);
        if (!p.edges.length) break;
        s = removeEdge(s, p.edges[0]);
        reparsed(s);
      }
      assert.equal(parseFlow(s).edges.length, 0);
    });
  }
});

// ===========================================================================
// the `state` cell — stateDiagram-v2
// ===========================================================================

const S = {
  parseState: state.parseState,
  detectDialect: state.detectDialect,
  SHAPES: state.SHAPES,
  ...Object.fromEntries(Object.entries(state.mutators))
};
const H = 'stateDiagram-v2\n';
const SUBSTRATE = FIXTURES.find((f) => f.name === 'stateDiagram_observable_substrate');
const STATE_KINDS = ['header', 'direction', 'state', 'transition', 'note',
                     'classDef', 'class', 'composite', 'end', 'comment', 'unknown'];

function checkStateSpans(parsed, src, trail) {
  const seen = new Set();
  const walk = (v, path) => {
    if (v === null || v === undefined || seen.has(v)) return;
    if (isSpan(v)) {
      assert.ok(v[0] >= 0, `${path}[0] >= 0 ${trail}`);
      assert.ok(v[1] <= src.length, `${path}[1] <= len ${trail}`);
      assert.ok(v[1] >= v[0], `${path} ordered ${trail}`);
      return;
    }
    if (v instanceof Map) { for (const [k, val] of v) walk(val, `${path}.${k}`); return; }
    if (Array.isArray(v)) { seen.add(v); v.forEach((x, i) => walk(x, `${path}[${i}]`)); return; }
    if (typeof v !== 'object') return;
    seen.add(v);
    for (const k of Object.keys(v)) walk(v[k], `${path}.${k}`);
  };
  walk({ h: parsed.header, n: parsed.nodes, e: parsed.edges, s: parsed.styles,
         c: parsed.composites, t: parsed.statements, x: parsed.errors }, '');
}

function checkStateRoundTrip(parsed, src, trail) {
  const eq = (span, text, what) => assert.equal(src.slice(span[0], span[1]), text, `${what} ${trail}`);
  assert.equal(parsed.src, src);
  for (const n of parsed.nodes.values()) {
    assert.notEqual(n.id, '[*]', `no \`[*]\` in nodes ${trail}`);
    for (const s of n.idSpans) eq(s, n.id, `node id ${n.id}`);
    if (n.decl) {
      eq(n.decl.idSpan, n.decl.id, `decl id ${n.id}`);
      assert.equal(n.decl.id, n.id);
      if (n.decl.labelSpan) eq(n.decl.labelSpan, n.decl.label, `decl label ${n.id}`);
      else assert.equal(n.decl.label, null, `unlabelled decl ${n.id}`);
      if (n.decl.shapeSpan) eq(n.decl.shapeSpan, `<<${n.decl.shape}>>`, `marker ${n.id}`);
      if (n.decl.kindSpan) assert.ok(n.decl.shapeSpan, `kindSpan implies a marker ${n.id}`);
      assert.ok(['state', 'fork', 'join', 'choice', 'composite'].includes(n.decl.shape), `known shape ${n.decl.shape}`);
    }
  }
  for (const e of parsed.edges) {
    eq(e.fromSpan, e.from, `edge from ${e.from}`);
    eq(e.toSpan, e.to, `edge to ${e.to}`);
    if (e.labelSpan) eq(e.labelSpan, e.label, 'edge label');
    else assert.equal(e.label, null);
    assert.equal(e.type, 'arrow');
    assert.equal(e.span[0], e.opSpan[0]);
    assert.ok(e.span[1] >= e.opSpan[1]);
    assert.match(src.slice(e.opSpan[0], e.opSpan[1]), /^-{2,}>$/);
    assert.equal(typeof e.depth, 'number');
  }
  for (const s of parsed.styles) {
    eq(s.bodySpan, s.body, 'style body');
    for (const t of s.targets) eq(t.span, t.name, 'style target');
  }
  for (const c of parsed.composites) {
    eq(c.idSpan, c.id, 'composite id');
    if (c.titleSpan) eq(c.titleSpan, c.title, 'composite title');
    assert.ok(c.bodySpan[0] >= c.span[0]);
    assert.ok(c.bodySpan[1] <= c.span[1]);
  }
  for (const s of parsed.statements) {
    assert.ok(STATE_KINDS.includes(s.kind), `known kind ${s.kind} ${trail}`);
    if (s.kind === 'note' && s.target) eq(s.targetSpan, s.target, 'note target');
  }
  if (parsed.header && parsed.header.dirSpan) {
    assert.equal(src.slice(parsed.header.dirSpan[0], parsed.header.dirSpan[1]).toUpperCase(), parsed.header.dir);
  }
}

/** Parses as a stateDiagram with zero errors, every span round-tripping. */
function okS(src) {
  const p = S.parseState(src);
  assert.deepEqual(p.errors, [], `errors for ${JSON.stringify(src)}`);
  checkStateSpans(p, src, JSON.stringify(src));
  checkStateRoundTrip(p, src, JSON.stringify(src));
  return p;
}
const reparsedS = (src) => okS(src);

describe('state: corpus fixture', () => {
  it('stateDiagram_observable_substrate parses with zero errors and every span round-trips', () => {
    const p = okS(SUBSTRATE.src);
    assert.equal(p.header.kind, 'stateDiagram-v2');
    assert.equal(p.header.dir, null);
    assert.equal(p.edges.length, 17);
    assert.ok(p.nodes.has('observablehq.com'));
    assert.equal(p.nodes.has('[*]'), false);
  });

  it('its composites nest, nodeIds are transitive, and edges carry composite depth', () => {
    const p = S.parseState(SUBSTRATE.src);
    assert.deepEqual(p.composites.map((c) => c.id), ['___.static.observableusercontent.com', 'static']);
    assert.deepEqual(p.composites.map((c) => c.depth), [0, 1]);
    const [outer, inner] = p.composites;
    assert.deepEqual(inner.nodeIds, ['main_module', 'runtime', 'stdlib', 'inspector']);
    for (const id of inner.nodeIds) assert.ok(outer.nodeIds.includes(id), id);
    assert.deepEqual(p.edges.map((e) => e.depth), [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 0]);
    assert.equal(p.nodes.get('___.static.observableusercontent.com').decl.shape, 'composite');
  });

  it('the flowchart fixtures are rejected by the state parser, not crashed', () => {
    for (const f of FIXTURES.filter((x) => x.name !== SUBSTRATE.name)) {
      const p = S.parseState(f.src);
      checkStateSpans(p, f.src, f.name);
      checkStateRoundTrip(p, f.src, f.name);
      assert.equal(p.header, null, f.name);
      assert.ok(p.errors.length > 0, f.name);
    }
  });

  it('detectDialect routes state, flow and neither', () => {
    assert.equal(S.detectDialect('stateDiagram-v2\nA --> B\n'), 'state');
    assert.equal(S.detectDialect('stateDiagram\nA --> B\n'), 'state');
    assert.equal(S.detectDialect('graph TD\nA-->B\n'), 'flow');
    assert.equal(S.detectDialect('flowchart LR\nA-->B\n'), 'flow');
    assert.equal(S.detectDialect('sequenceDiagram\nA->>B: hi\n'), null);
    assert.equal(S.detectDialect(null), null);
    assert.equal(S.detectDialect('\n\n  %% a directive\n   stateDiagram-v2\nA --> B\n'), 'state');
    assert.equal(S.detectDialect(SUBSTRATE.src), 'state');
    for (const f of FLOWCHARTS) assert.equal(S.detectDialect(f.src), 'flow', f.name);
  });
});

describe('state: structure', () => {
  it('both header spellings, and `direction` lifted onto the header', () => {
    assert.equal(okS(H + 'A --> B\n').header.kind, 'stateDiagram-v2');
    assert.equal(okS('stateDiagram\nA --> B\n').header.kind, 'stateDiagram');
    for (const d of ['TB', 'TD', 'LR', 'RL', 'BT']) {
      const p = okS(`${H}direction ${d}\nA --> B\n`);
      assert.equal(p.header.dir, d);
      assert.equal(p.statements[1].kind, 'direction');
    }
    // a direction inside a composite is not the header's
    assert.equal(okS(`${H}state S {\ndirection LR\nA --> B\n}\n`).header.dir, null);
    assert.equal(S.parseState(`${H}direction ZZ\n`).errors.length, 1);
  });

  it('decl form: state "Description" as id', () => {
    const p = okS(`${H}state "the first one" as S1\nS1 --> S2\n`);
    const d = p.nodes.get('S1').decl;
    assert.equal(d.form, 'as');
    assert.equal(d.shape, 'state');
    assert.equal(d.label, 'the first one');
    assert.equal(p.src[d.labelSpan[0] - 1], '"');
    assert.equal(p.statements[1].kind, 'state');
  });

  it('decl form: id: Description, keeping inner colons and quotes', () => {
    const d = okS(`${H}A --> B\nA: does the thing\n`).nodes.get('A').decl;
    assert.equal(d.form, 'colon');
    assert.equal(d.label, 'does the thing');
    assert.equal(d.shape, 'state');
    assert.equal(okS(`${H}A: he said "10:30"\n`).nodes.get('A').decl.label, 'he said "10:30"');
  });

  it('decl forms: bare id, `state id`, and the <<fork>>/<<join>>/<<choice>> markers', () => {
    const p = okS(`${H}state Alone\nBare\n`);
    assert.equal(p.nodes.get('Alone').decl.form, 'state');
    assert.equal(p.nodes.get('Alone').decl.label, null);
    assert.equal(p.nodes.get('Bare').decl.form, 'bare');
    for (const kind of ['fork', 'join', 'choice']) {
      const q = okS(`${H}state F <<${kind}>>\nA --> F\n`);
      const d = q.nodes.get('F').decl;
      assert.equal(d.shape, kind);
      assert.equal(q.src.slice(d.shapeSpan[0], d.shapeSpan[1]), `<<${kind}>>`);
    }
    assert.equal(S.parseState(`${H}state F <<spork>>\n`).errors.length, 1);
  });

  it('transitions with and without a label, and no-space / long-dash forms', () => {
    const p = okS(`${H}A --> B\n`);
    assert.deepEqual([p.edges[0].from, p.edges[0].to, p.edges[0].label, p.edges[0].type], ['A', 'B', null, 'arrow']);
    assert.equal(p.src.slice(p.edges[0].statementSpan[0], p.edges[0].statementSpan[1]), 'A --> B');
    assert.equal(okS(`${H}A --> B:   a label with spaces   \n`).edges[0].label, 'a label with spaces');
    assert.equal(okS(`${H}A --> B: {"at": "10:30"}\n`).edges[0].label, '{"at": "10:30"}');
    assert.equal(okS(`${H}A --> B:\n`).edges[0].label, '', 'an empty label is "" not null');
    assert.equal(okS(`${H}A-->B\n`).edges[0].to, 'B');
    assert.equal(okS(`${H}A ----> B\n`).edges[0].to, 'B');
    // a chain is not supported here, and reports rather than crashing
    assert.match(S.parseState(`${H}A --> B --> C\n`).errors[0].message, /trailing text/);
  });

  it('`[*]` on either side never enters nodes', () => {
    const p = okS(`${H}[*] --> A\nA --> [*]\n[*] --> [*]\n`);
    assert.deepEqual(p.edges.map((e) => `${e.from}>${e.to}`), ['[*]>A', 'A>[*]', '[*]>[*]']);
    assert.deepEqual([...p.nodes.keys()], ['A']);
  });

  it('composites: `state id { … }`, the described form, and nesting depth', () => {
    const src = `${H}state Big {\n  A --> B\n}\nC --> Big\n`;
    const p = okS(src);
    const c = p.composites[0];
    assert.equal(c.id, 'Big');
    assert.equal(c.title, null);
    assert.deepEqual(c.nodeIds, ['A', 'B']);
    assert.equal(src.slice(c.bodySpan[0], c.bodySpan[1]).trim(), 'A --> B');
    assert.equal(p.nodes.get('Big').decl.shape, 'composite');
    assert.deepEqual(p.statements.map((s) => s.kind), ['header', 'composite', 'transition', 'end', 'transition']);
    const q = okS(`${H}state "a big one" as Big {\n  A --> B\n}\n`);
    assert.equal(q.composites[0].title, 'a big one');
    const r = okS(`${H}state A {\nstate B {\nstate C {\nX --> Y\n}\n}\n}\n`);
    assert.deepEqual(r.composites.map((x) => x.depth), [0, 1, 2]);
    assert.equal(r.edges[0].depth, 3);
    assert.match(S.parseState(`${H}state A {\nX --> Y\n`).errors[0].message, /never closed/);
  });

  it('notes: one-liners either side, and a block note is ONE statement', () => {
    const p = okS(`${H}A --> B\nnote right of A : it starts here\nnote left of B: and ends here\n`);
    const notes = p.statements.filter((s) => s.kind === 'note');
    assert.deepEqual(notes.map((n) => n.target), ['A', 'B']);
    assert.deepEqual(notes.map((n) => n.side), ['right', 'left']);
    assert.equal(notes[0].text, 'it starts here');
    const src = `${H}A --> B\nnote left of A\n  line one\n  line two\nend note\nB --> C\n`;
    const q = okS(src);
    assert.deepEqual(q.statements.map((s) => s.kind), ['header', 'transition', 'note', 'transition']);
    assert.equal(src.slice(q.statements[2].span[0], q.statements[2].span[1]),
      'note left of A\n  line one\n  line two\nend note');
    // the note registers its target, so the state stays renameable
    assert.equal(okS(`${H}A --> B\nnote right of A : x\n`).nodes.get('A').idSpans.length, 2);
  });

  it('never throws on junk', () => {
    for (const j of ['', null, undefined, 'stateDiagram-v2', '}}}', 'state', 'state "unterminated as X',
                     'A -->', 'note right of', '%%', '"', '{', `${H}state {\n`]) {
      const p = S.parseState(j);
      const s = j === null || j === undefined ? '' : String(j);
      checkStateSpans(p, s, JSON.stringify(j));
      checkStateRoundTrip(p, s, JSON.stringify(j));
    }
    const p = S.parseState(`${H}A --> B\nthis is not a statement\nC --> D\n`);
    assert.equal(p.errors.length, 1);
    assert.equal(p.edges.length, 2);
  });
});

describe('state: mutators', () => {
  it('setLabel rewrites each decl form, promotes a bare id, and clears back', () => {
    assert.equal(S.setLabel(`${H}state "old" as A\nA --> B\n`, 'A', 'new'), `${H}state "new" as A\nA --> B\n`);
    assert.equal(S.setLabel(`${H}A --> B\nA: old\n`, 'A', 'new one'), `${H}A --> B\nA: new one\n`);
    assert.equal(S.setLabel(`${H}state A\nA --> B\n`, 'A', 'described'), `${H}state "described" as A\nA --> B\n`);
    assert.equal(S.setLabel(`${H}state F <<fork>>\nA --> F\n`, 'F', 'the fork'), `${H}state "the fork" as F <<fork>>\nA --> F\n`);
    assert.equal(S.setLabel(`${H}A --> B\n`, 'A', 'described'), `${H}A --> B\nA: described\n`);
    assert.equal(S.setLabel(`${H}state "old" as S {\nA --> B\n}\n`, 'S', 'new'), `${H}state "new" as S {\nA --> B\n}\n`);
    assert.equal(reparsedS(S.setLabel(`${H}A --> B\n`, 'A', 'described')).nodes.get('A').decl.form, 'colon');
    // empty text drops the description
    assert.equal(S.setLabel(`${H}A --> B\nA: gone\n`, 'A', ''), `${H}A --> B\n`);
    assert.equal(S.setLabel(`${H}state "x" as A\nA --> B\n`, 'A', ''), `${H}state A\nA --> B\n`);
    assert.throws(() => S.setLabel(`${H}A: x\n`, 'A', 'one\ntwo'));
    assert.throws(() => S.setLabel(`${H}A --> B\n`, 'Z', 'x'));
  });

  it('setShape adds, replaces and (as `state`) strips a <<kind>> marker', () => {
    assert.equal(S.SHAPES.join(), 'state,fork,join,choice');
    for (const kind of ['fork', 'join', 'choice']) {
      const out = S.setShape(`${H}state F\nA --> F\n`, 'F', kind);
      assert.equal(out, `${H}state F <<${kind}>>\nA --> F\n`);
      assert.equal(reparsedS(out).nodes.get('F').decl.shape, kind);
    }
    assert.equal(S.setShape(`${H}state F <<fork>>\nA --> F\n`, 'F', 'join'), `${H}state F <<join>>\nA --> F\n`);
    // 'state' removes the marker, and keeps a description
    assert.equal(S.setShape(`${H}state F <<fork>>\nA --> F\n`, 'F', 'state'), `${H}state F\nA --> F\n`);
    assert.equal(S.setShape(`${H}state "the fork" as F <<fork>>\nA --> F\n`, 'F', 'state'), `${H}state "the fork" as F\nA --> F\n`);
    assert.equal(S.setShape(`${H}state F\nA --> F\n`, 'F', 'state'), `${H}state F\nA --> F\n`, 'no-op when unmarked');
    assert.throws(() => S.setShape(`${H}state F\n`, 'F', 'composite'));
    assert.throws(() => S.setShape(`${H}state S {\nA --> B\n}\n`, 'S', 'fork'));
  });

  it('setShape on the colon form puts the marker on its own line, folded into one decl', () => {
    const out = S.setShape(`${H}A --> D\nD: Publish\n`, 'D', 'join');
    assert.equal(out, `${H}A --> D\nD: Publish\nstate D <<join>>\n`);
    const d = reparsedS(out).nodes.get('D').decl;
    assert.equal(d.shape, 'join');
    assert.equal(d.label, 'Publish');
    assert.equal(d.form, 'colon');
    // a second call rewrites that line rather than adding another
    assert.equal(S.setShape(out, 'D', 'fork'), `${H}A --> D\nD: Publish\nstate D <<fork>>\n`);
    // and `state` deletes the marker-only line, keeping the description
    const back = S.setShape(out, 'D', 'state');
    assert.equal(back, `${H}A --> D\nD: Publish\n`);
    assert.equal(reparsedS(back).nodes.get('D').decl.label, 'Publish');
  });

  it('addEdge appends at the top level, honours a label and `[*]`', () => {
    assert.equal(S.addEdge(`${H}  A --> B\n`, 'B', 'C'), `${H}  A --> B\n  B --> C\n`);
    assert.equal(S.addEdge(`${H}A --> B\n`, 'B', 'C', { label: 'then' }), `${H}A --> B\nB --> C: then\n`);
    let s = S.addEdge(`${H}A --> B\n`, '[*]', 'A');
    s = S.addEdge(s, 'B', '[*]');
    assert.deepEqual(reparsedS(s).edges.map((e) => `${e.from}>${e.to}`), ['A>B', '[*]>A', 'B>[*]']);
    // never lands inside a composite
    assert.equal(S.addEdge(`${H}A --> B\nstate S {\n  C --> D\n}\n`, 'B', 'C'),
      `${H}A --> B\nB --> C\nstate S {\n  C --> D\n}\n`);
    assert.equal(S.addEdge(H, 'A', 'B'), `${H}A --> B\n`);
    assert.throws(() => S.addEdge(`${H}A --> B\n`, 'A B', 'C'));
  });

  it('addNode appends the described form, or `state id` when unlabelled', () => {
    const out = S.addNode(`${H}A --> B\n`, 'C', 'a third');
    assert.equal(out, `${H}A --> B\nstate "a third" as C\n`);
    assert.equal(reparsedS(out).nodes.get('C').decl.label, 'a third');
    assert.equal(S.addNode(`${H}A --> B\n`, 'C'), `${H}A --> B\nstate C\n`);
    assert.equal(S.addNode(`${H}A --> B\nstate S {\n  C --> D\n}\n`, 'E', 'e'),
      `${H}A --> B\nstate "e" as E\nstate S {\n  C --> D\n}\n`);
    assert.throws(() => S.addNode(`${H}A --> B\n`, 'A', 'x'));
    assert.throws(() => S.addNode(`${H}A --> B\n`, 'C', 'say "hi"'));
  });

  it('setEdgeLabel adds, rewrites and clears a `: label`', () => {
    const edit = (src, pick, text) => S.setEdgeLabel(src, S.parseState(src).edges.find(pick), text);
    assert.equal(edit(`${H}A --> B\n`, () => true, 'when ready'), `${H}A --> B: when ready\n`);
    assert.equal(edit(`${H}A --> B: old\nC --> D\n`, (e) => e.from === 'A', 'new'), `${H}A --> B: new\nC --> D\n`);
    assert.equal(edit(`${H}A --> B : old\n`, () => true, ''), `${H}A --> B\n`);
    assert.equal(edit(`${H}A --> B\n`, () => true, ''), `${H}A --> B\n`, 'clearing an absent label is a no-op');
    assert.equal(edit(`${H}A --> B:\n`, () => true, 'now'), `${H}A --> B: now\n`);
    // targets the right transition inside a composite
    assert.equal(edit(`${H}A --> B\nstate S {\n  C --> D\n}\n`, (e) => e.from === 'C', 'inner'),
      `${H}A --> B\nstate S {\n  C --> D: inner\n}\n`);
    assert.equal(reparsedS(edit(`${H}A --> B\n`, () => true, '<a href="x">10:30</a>')).edges[0].label, '<a href="x">10:30</a>');
    assert.throws(() => edit(`${H}A --> B\n`, () => true, 'a\nb'));
    assert.throws(() => S.setEdgeLabel(`${H}ZZZZZZ --> B\n`, S.parseState(`${H}A --> B\n`).edges[0], 'x'));
  });

  it('removeEdge takes the whole transition line', () => {
    const drop = (src, pick) => S.removeEdge(src, S.parseState(src).edges.find(pick));
    assert.equal(drop(`${H}A --> B\nC --> D\n`, (e) => e.from === 'A'), `${H}C --> D\n`);
    assert.equal(drop(`${H}A --> B\n`, () => true), H);
    assert.equal(drop(`${H}state S {\n  C --> D: x\n  E --> F\n}\n`, (e) => e.from === 'C'), `${H}state S {\n  E --> F\n}\n`);
    assert.equal(drop(`${H}[*] --> A\nA --> B\n`, (e) => e.from === '[*]'), `${H}A --> B\n`);
    assert.throws(() => S.removeEdge(`${H}C --> D\n`, S.parseState(`${H}A --> B\n`).edges[0]));
  });

  it('removeNode takes every declaring statement, transition, note and composite block', () => {
    assert.equal(S.removeNode(`${H}A --> D\nD: Publish\nstate D <<join>>\nstate D\nA --> Z\n`, 'D'), `${H}A --> Z\n`);
    const out = S.removeNode(`${H}A --> B\nB --> C\nB: a description\nstate B\nnote right of B : hi\nA --> C\n`, 'B');
    assert.equal(out, `${H}A --> C\n`);
    assert.equal(reparsedS(out).nodes.has('B'), false);
    assert.equal(S.removeNode(`${H}A --> B\nnote left of B\n  text\nend note\nA --> C\n`, 'B'), `${H}A --> C\n`);
    const flat = S.removeNode(`${H}A --> S\nstate S {\n  C --> D\n  state T {\n    E --> F\n  }\n}\nA --> Z\n`, 'S');
    assert.equal(flat, `${H}A --> Z\n`);
    assert.equal(reparsedS(flat).composites.length, 0);
    assert.equal(S.removeNode(`${H}A --> B\n`, 'Z'), `${H}A --> B\n`, 'unknown state is a no-op');
    assert.throws(() => S.removeNode(`${H}[*] --> A\n`, '[*]'));
  });

  it('renameNode rewrites decl, transitions, note target and class list only', () => {
    const src = `${H}state "the one" as A\nA --> B\nB --> A: back\nnote right of A : hi\nclass A hot\n`;
    const out = S.renameNode(src, 'A', 'Z');
    assert.equal(out, `${H}state "the one" as Z\nZ --> B\nB --> Z: back\nnote right of Z : hi\nclass Z hot\n`);
    const p = reparsedS(out);
    assert.equal(p.nodes.has('A'), false);
    assert.equal(p.nodes.get('Z').decl.label, 'the one');
    // a description that merely contains the id is left alone
    assert.equal(S.renameNode(`${H}A --> B\nA: A is the start\n`, 'A', 'Z'), `${H}Z --> B\nZ: A is the start\n`);
    assert.equal(S.renameNode(`${H}state S {\n  C --> D\n}\nA --> S\n`, 'S', 'Big'), `${H}state Big {\n  C --> D\n}\nA --> Big\n`);
    assert.throws(() => S.renameNode(`${H}A --> B\n`, 'Z', 'Y'));
    assert.throws(() => S.renameNode(`${H}A --> B\n`, 'A', '[*]'));
  });

  it('setDirection replaces, inserts after the header, or prepends a whole header', () => {
    assert.equal(S.setDirection(`${H}direction TB\nA --> B\n`, 'LR'), `${H}direction LR\nA --> B\n`);
    assert.equal(S.setDirection(`${H}A --> B\n`, 'RL'), `${H}direction RL\nA --> B\n`);
    assert.equal(S.setDirection('A --> B\n', 'TD'), `${H}direction TD\nA --> B\n`);
    // a direction inside a composite is not the one being set
    assert.equal(S.setDirection(`${H}state S {\ndirection LR\nA --> B\n}\n`, 'BT'),
      `${H}direction BT\nstate S {\ndirection LR\nA --> B\n}\n`);
    assert.equal(reparsedS(S.setDirection(`${H}A --> B\n`, 'lr')).header.dir, 'LR');
    assert.throws(() => S.setDirection(`${H}A --> B\n`, 'ZZ'));
  });

  it('the state mutators registry lists every rewriting helper and nothing else', () => {
    assert.deepEqual(Object.keys(state.mutators).sort(), [
      'addComposite', 'addEdge', 'addNode', 'moveNode', 'removeComposite', 'removeEdge', 'removeNode', 'renameNode',
      'setClassDef', 'setCompositeDirection', 'setCompositeTitle', 'setDirection', 'setEdgeLabel', 'setLabel', 'setNodeClass', 'setNote', 'setShape'
    ]);
    for (const name of Object.keys(state.mutators)) {
      assert.equal(typeof state.mutators[name], 'function', name);
      assert.equal(state.mutators[name].name, name, name);
    }
    assert.equal(state.mutators.addNode, state.addNode);
  });
});

describe('state: mutations on the real fixture', () => {
  it('a round of edits stays parseable and carries every change', () => {
    let s = SUBSTRATE.src;
    s = S.setLabel(s, 'cell', 'a notebook cell');
    assert.equal(reparsedS(s).nodes.get('cell').decl.label, 'a notebook cell');
    s = S.setLabel(s, 'cell', '');
    assert.equal(reparsedS(s).nodes.get('cell').decl, null);
    s = S.addNode(s, 'EXTRA', 'an extra state');
    s = S.setShape(s, 'EXTRA', 'choice');
    assert.ok(s.includes('state EXTRA <<choice>>'));
    assert.equal(reparsedS(s).nodes.get('EXTRA').decl.shape, 'choice');
    assert.equal(reparsedS(s).nodes.get('EXTRA').decl.label, 'an extra state');
    s = S.addEdge(s, '[*]', 'EXTRA', { label: 'start here' });
    assert.ok(reparsedS(s).edges.some((e) => e.from === '[*]' && e.label === 'start here'));
    s = S.renameNode(s, 'EXTRA', 'Renamed');
    assert.ok(reparsedS(s).nodes.has('Renamed'));
    s = S.removeNode(s, 'Renamed');
    assert.equal(reparsedS(s).nodes.has('Renamed'), false);
    s = S.setDirection(s, 'LR');
    assert.equal(reparsedS(s).header.dir, 'LR');
    s = S.setEdgeLabel(s, S.parseState(s).edges[0], 'tagged');
    assert.equal(reparsedS(s).edges[0].label, 'tagged');
    s = S.setEdgeLabel(s, S.parseState(s).edges[0], '');
    assert.equal(reparsedS(s).edges[0].label, null);
  });

  it('every transition, then every state, can be removed one at a time', () => {
    let s = SUBSTRATE.src;
    for (let guard = 0; guard < 50; guard++) {
      const p = S.parseState(s);
      if (!p.edges.length) break;
      s = S.removeEdge(s, p.edges[0]);
      reparsedS(s);
    }
    assert.equal(S.parseState(s).edges.length, 0);
    let t = SUBSTRATE.src;
    for (let guard = 0; guard < 50; guard++) {
      const ids = [...S.parseState(t).nodes.keys()];
      if (!ids.length) break;
      t = S.removeNode(t, ids[0]);
      reparsedS(t);
    }
    assert.equal(S.parseState(t).nodes.size, 0);
  });
});

// ===========================================================================
// the `dialects` cell — one interface over both DSLs
// ===========================================================================

describe('dialects', () => {
  const UNIFORM = ['parse', 'shapes', 'nodeIdOf', 'edgeOf', 'name', 'edgeSelector',
                   'setLabel', 'setShape', 'setDirection', 'renameNode',
                   'addEdge', 'setEdgeLabel', 'removeEdge', 'removeNode', 'addNode'];

  it('of() picks the dialect from the header, and null for anything else', () => {
    assert.equal(dialects.of('graph TD\nA-->B\n'), dialects.flow);
    assert.equal(dialects.of('flowchart LR\nA-->B\n'), dialects.flow);
    assert.equal(dialects.of(`${H}A --> B\n`), dialects.state);
    assert.equal(dialects.of('stateDiagram\nA --> B\n'), dialects.state);
    assert.equal(dialects.of('sequenceDiagram\nA->>B: hi\n'), null);
    assert.equal(dialects.of(''), null);
    for (const f of FLOWCHARTS) assert.equal(dialects.of(f.src), dialects.flow, f.name);
    assert.equal(dialects.of(SUBSTRATE.src), dialects.state);
  });

  it('both dialects expose the same method names, wired to the real cells', () => {
    for (const d of [dialects.flow, dialects.state]) {
      for (const k of UNIFORM) assert.ok(k in d, `${d.name} is missing ${k}`);
      assert.ok(Array.isArray(d.shapes) && d.shapes.length > 0, `${d.name} shapes`);
      for (const k of ['parse', 'nodeIdOf', 'edgeOf', 'setLabel', 'setShape', 'setDirection',
                       'renameNode', 'addEdge', 'setEdgeLabel', 'removeEdge', 'removeNode', 'addNode']) {
        assert.equal(typeof d[k], 'function', `${d.name}.${k}`);
      }
    }
    assert.equal(dialects.flow.parse, parseFlow);
    assert.equal(dialects.state.parse, state.parseState);
    assert.equal(dialects.state.setStyle, null, 'stateDiagram has no `style` statement');
    assert.deepEqual(dialects.flow.shapes, Object.keys(SHAPES));
    assert.deepEqual(dialects.state.shapes, state.SHAPES);
  });

  it('the chosen dialect parses and mutates its own source through the uniform interface', () => {
    for (const src of [FLOWCHARTS[0].src, SUBSTRATE.src]) {
      const d = dialects.of(src);
      const p = d.parse(src);
      assert.deepEqual(p.errors, [], d.name);
      const id = [...p.nodes.keys()][0];
      const out = d.setDirection(d.renameNode(src, id, 'Renamed'), 'LR');
      const q = d.parse(out);
      assert.deepEqual(q.errors, [], d.name);
      assert.ok(q.nodes.has('Renamed'), d.name);
      assert.equal(q.header.dir, 'LR', d.name);
      // nodeIdOf reads mermaid's own SVG id convention for this dialect
      assert.equal(d.nodeIdOf({ id: `${d.name === 'flow' ? 'flowchart' : 'state'}-Renamed-1`, classList: new Set() }, q), 'Renamed');
    }
  });
});

process.on('beforeExit', () => imported.dispose());
