// Join -> edit -> go offline -> edit offline -> go online keeping -> offline edit -> online discarding -> disconnect.
import { chromium } from "playwright";
const nb = process.argv[2]!, url = process.argv[3]!, out = process.argv[4]!;
const b = await chromium.launch();
const c = await b.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1280, height: 800 } });
const p = await c.newPage();
p.on("pageerror", (e) => console.log("  [pageerror]", String(e).slice(0, 160)));
p.on("dialog", (d) => d.accept(d.type() === "prompt" ? url : undefined));
const raw = async () => (await (await c.request.get(url + "?raw")).text());
const frag = (h: string) => /<code-fragment[^>]*>([\s\S]*?)<\/code-fragment>/i.exec(h)?.[1]?.trim();
const val = (n: string) => p.evaluate((n) => [...(window as any).__ojs_runtime._variables].find((v: any) => v._name === n && v._module?._scope?.has("codestratePlace"))?._value, n);
const frameOf = async () => (await (await p.locator(".codestrate iframe").first().elementHandle())!.contentFrame())!;
const statusText = () => p.locator("text=/Synced live|Offline|Not connected|Connecting|Could not/").first().textContent();
const buttons = () => p.evaluate(() => [...document.querySelectorAll("button")].map((b) => b.textContent).filter((t) => /online|offline|Disconnect|Copy to|Sync with/i.test(t!)));
const edit = async (step: string) => {
  const f = await frameOf();
  const ok = await f.locator("#cauldron-edit-button").waitFor({ timeout: 45000 }).then(() => true, () => false);
  console.log(`[${step}] status: ${await statusText()} | Edit: ${ok ? "yes" : "MISSING"} | frame fragment: ${frag(await f.content())} | buttons: ${JSON.stringify(await buttons())}`);
  if (!ok) await p.screenshot({ path: `${out}/journey-${step}.png` });
  return f;
};
const setFrag = (f: any, t: string) => f.evaluate((t: string) => { document.querySelector("code-fragment")!.textContent = t; }, t);
await p.goto(`file://${nb}`);
await edit("0 start");
await p.getByRole("button", { name: "Sync with a webstrate…" }).click();
await p.getByText(/Synced live/).waitFor({ timeout: 60000 });
let f = await edit("1 joined");
await setFrag(f, "edited while synced");
await p.waitForTimeout(3000);
console.log("  server fragment:", frag(await raw()));
await p.getByRole("button", { name: "Go offline" }).click();
f = await edit("2 offline, unchanged");
await c.setOffline(true);
await setFrag(f, "edited while offline");
await p.waitForTimeout(2000);
f = await edit("3 offline, changed");
await c.setOffline(false);
await p.getByRole("button", { name: "Go online, keeping my changes" }).click();
await p.getByText(/Synced live/).waitFor({ timeout: 60000 });
f = await edit("4 online, kept");
let r = await raw();
console.log("  server fragment:", frag(r), "| bootconfig:", r.includes("json+bootconfig"), "| WPM:", r.includes("WPMv2-script"));
await p.getByRole("button", { name: "Go offline" }).click();
f = await edit("5 offline");
await setFrag(f, "offline edit to discard");
await p.waitForTimeout(2000);
await p.getByRole("button", { name: "Go online, discarding my changes" }).click();
await p.getByText(/Synced live/).waitFor({ timeout: 60000 });
f = await edit("6 online, discarded");
console.log("  cell fragment:", frag(String(await val("doc"))), "| server fragment:", frag(await raw()));
await p.getByRole("button", { name: "Disconnect" }).click();
await edit("7 disconnected");
await p.screenshot({ path: `${out}/journey-end.png` });
await b.close();
