// Offline-style edit in "this notebook" mode, then "Overwrite the webstrate with this copy…".
import { chromium } from "playwright";
const nb = process.argv[2]!, url = process.argv[3]!, out = process.argv[4]!;
const b = await chromium.launch();
const c = await b.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1280, height: 800 } });
const raw = async () => (await (await c.request.get(url + "?raw")).text());
console.log("server before:", (await raw()).replace(/\s+/g, " ").slice(0, 160));
const p = await c.newPage();
p.on("pageerror", (e) => console.log("[pageerror]", String(e).slice(0, 200)));
p.on("dialog", (d) => d.accept());
const val = (name: string) => p.evaluate((n) => [...(window as any).__ojs_runtime._variables].find((v: any) => v._name === n && v._module?._scope?.has("codestratePlace"))?._value, name);
const frameOf = async () => (await (await p.locator("iframe").first().elementHandle())!.contentFrame())!;
await p.goto(`file://${nb}`);
await p.waitForFunction(() => [...((window as any).__ojs_runtime?._variables ?? [])].some((v: any) => v._name === "viewof place" && v._value));
await p.evaluate((url) => { [...(window as any).__ojs_runtime._variables].find((v: any) => v._name === "viewof place")._value.value = { where: "notebook", url }; }, url);
let f = await frameOf();
await f.locator("#cauldron-edit-button").waitFor({ timeout: 60000 });
await f.locator("#app button").click(); await f.locator("#app button").click(); await f.locator("#app button").click();
await p.waitForTimeout(1500);
console.log("local copy count:", /data-count="(\d+)"/.exec(await val("doc"))?.[1], "overwrite button visible:", await p.getByRole("button", { name: /Overwrite the webstrate/ }).isVisible());
await p.getByRole("button", { name: /Overwrite the webstrate/ }).click();
await p.getByText(/Overwriting/).waitFor({ timeout: 60000 }).then(() => console.log("saw: Overwriting…"));
await p.getByText(/Synced live with/).waitFor({ timeout: 60000 });
f = await frameOf();
await f.locator("#cauldron-edit-button").waitFor({ timeout: 60000 });
await p.waitForTimeout(2000);
const r = await raw();
console.log("server after: count", /data-count="(\d+)"/.exec(r)?.[1], "| first version gone:", !r.includes("first version"), "| fragments:", (r.match(/<code-fragment/gi) || []).length, "| transient/blob junk:", /\btransient\b|blob:/.test(r.replace(/<script id="lopecode-bridge"[\s\S]*?<\/script>/, "")));
console.log("frame after reload: count", await f.locator("#app").getAttribute("data-count"), "| cell count", /data-count="(\d+)"/.exec(await val("doc"))?.[1], "| place", JSON.stringify(await val("place")));
const q = await c.newPage();
await q.goto(url);
await q.locator("#app button").waitFor({ timeout: 60000 });
console.log("server-hosted page shows count:", await q.locator("#app").getAttribute("data-count"), "text:", (await q.locator("#app button").textContent()));
await p.screenshot({ path: `${out}/overwrite.png` });
await Bun.write(out + "/overwrite-raw.html", r);
await b.close();
