// Notebook -> upload -> synced frame: local click reaches server + cell; server-page click reaches frame + cell; offline reload falls back.
import { chromium } from "playwright";
const nb = process.argv[2]!, out = process.argv[3]!;
const b = await chromium.launch();
const c = await b.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1280, height: 800 } });
const p = await c.newPage();
p.on("pageerror", (e) => console.log("[pageerror]", String(e).slice(0, 200)));
p.on("console", (m) => { if (m.type() === "error") console.log("[console]", m.text().slice(0, 160)); });
p.on("dialog", (d) => d.accept(d.defaultValue() || undefined));
const val = (name: string) => p.evaluate((n) => [...(window as any).__ojs_runtime._variables].find((v: any) => v._name === n && v._module?._scope?.has("codestratePlace"))?._value, name);
const cellSynced = async () => Bun.write(out + "/cell-synced.html", String(await val("doc")));
const docCount = async () => /data-count="(\d+)"/.exec(await val("doc"))?.[1];
const frameOf = async () => (await (await p.locator("iframe").first().elementHandle())!.contentFrame())!;
await p.goto(`file://${nb}`);
await (await frameOf()).locator("#cauldron-edit-button").waitFor({ timeout: 60000 });
await p.getByRole("button", { name: /Copy to a Webstrates server/ }).click();
await p.getByText(/Synced live with|Could not reach/).waitFor({ timeout: 60000 });
console.log("status:", await p.locator("text=/Synced live with|Could not reach/").first().textContent(), JSON.stringify(await val("place")));
const url = (await val("place")).url;
const f = await frameOf();
await f.locator("#cauldron-edit-button").waitFor({ timeout: 60000 });
console.log("synced frame booted Codestrates; loader gone:", !(await f.content()).includes("Connecting to"));
await p.waitForTimeout(2000);
await f.locator("#app button").click();
await p.waitForTimeout(2500);
const raw = async () => (await (await c.request.get(url + "?raw")).text());
let r = await raw();
console.log("after local click: frame", await f.locator("#app").getAttribute("data-count"), "| server", /data-count="(\d+)"/.exec(r)?.[1], "| cell", await docCount());
const noBridge = (h: string) => h.replace(/<script id="lopecode-bridge">[\s\S]*?<\/script>/, "");
console.log("server doc junk: blob:", noBridge(r).includes("blob:"), "requirejs nodes:", r.includes("data-requiremodule"), "monaco css:", r.includes("editor.main.css"), "length", r.length);
console.log("cell has __wid or blob:", /__wid|blob:/.test(noBridge(String(await val("doc")))));
// another client: the server's own page
const q = await c.newPage();
await q.goto(url);
await q.locator("#app button").waitFor({ timeout: 60000 });
await q.waitForTimeout(3000);
await q.locator("#app button").click();
await p.waitForTimeout(3000);
console.log("after server-page click: frame", await f.locator("#app").getAttribute("data-count"), "| server-page", await q.locator("#app").getAttribute("data-count"), "| cell", await docCount());
await p.screenshot({ path: `${out}/sync-live.png` });
await cellSynced();
// offline: switch to notebook and back to sync with the network off
await q.close();
await c.setOffline(true);
await p.locator("select").first().selectOption("notebook");
await p.waitForTimeout(3000);
await p.locator("select").first().selectOption("sync");
await p.getByText(/Could not reach|Synced live/).waitFor({ timeout: 60000 });
console.log("offline status:", await p.locator("text=/Could not reach|Synced live/").first().textContent());
const g = await frameOf();
await g.locator("#cauldron-edit-button").waitFor({ timeout: 60000 });
console.log("offline frame booted; WPM src restored in cell:", String(await val("doc")).includes('id="WPMv2-script" type="text/javascript" src="https://cdn.jsdelivr'), "count:", await g.locator("#app").getAttribute("data-count"), "place:", JSON.stringify(await val("place")));
console.log("webstrate:", url);
await Bun.write(out + "/cell-after.html", String(await val("doc")));
await b.close();
