-- ============================================================
-- kb/views.sql — DuckDB views over lopecode-dev's committed JSON
-- ============================================================
-- Run from the lopecode-dev repo root:
--   duckdb -init kb/views.sql -c "SELECT * FROM kb_triples LIMIT 10"
--
-- See knowledge/querying-and-maintaining-the-lopecode-structured-knowledgebase.md
-- for the predicate vocabulary, design rationale, and maintenance notes.
--
-- Source files (all tracked in git):
--   content.json                                   — module catalogue (observableUrl, publishedAt)
--   {lopecode,lopebooks}/notebooks/@*.json         — per-notebook specs (regenerated by jumpgate via lope-reader.ts)
-- ============================================================

-- ---------- Source views (1:1 with the JSON files) ----------

-- content.json structure: { version, categories: [...], entries: [...] }
-- Each entry has: slug, url, title, description, sourceUrl, category, ...
CREATE OR REPLACE VIEW catalogue AS
SELECT entry.* FROM (
  SELECT UNNEST(entries) AS entry
  FROM read_json_auto('content.json', maximum_object_size=104857600)
);

-- Per-notebook spec files. Each file is one JSON object:
--   { notebook, title, bootconf, files, modules: { "<slug>": {hash, files?}, ... } }
-- read_json_objects keeps each file as a single JSON value, which avoids the
-- schema-union explosion that read_json_auto would produce across heterogeneous
-- notebooks (different module key sets).
--
-- The glob is `*.json` (not `@*.json`) so it picks up custom-named bundles
-- like `atproto.json`, `jumpgates.json`, `ledger.json`, `lopefeed.json` —
-- multi-source bundles where the filename doesn't start with `@`. Filename
-- determinism (only spec files live next to .html files) keeps the union safe.
CREATE OR REPLACE VIEW notebook_specs AS
SELECT json::JSON AS spec FROM read_json_objects(
  ['lopecode/notebooks/*.json', 'lopebooks/notebooks/*.json']
);

-- ---------- Triple-shaped views (one per predicate) ----------

-- module → observableUrl → URL
CREATE OR REPLACE VIEW kb_observable_url AS
SELECT slug AS subject, 'observableUrl' AS predicate, sourceUrl AS object
FROM catalogue
WHERE sourceUrl IS NOT NULL;

-- module → publishedAt → URL  (GitHub Pages location)
CREATE OR REPLACE VIEW kb_published_at AS
SELECT slug AS subject, 'publishedAt' AS predicate, url AS object
FROM catalogue
WHERE url IS NOT NULL;

-- notebook → containsModule → module
-- Derived from the per-notebook spec's `modules` object — its keys are exactly
-- the modules bundled into that notebook. Deduplicated because the same
-- notebook id may appear in both lopecode/ and lopebooks/.
CREATE OR REPLACE VIEW kb_contains_module AS
SELECT DISTINCT
  json_extract_string(spec, '$.notebook') AS subject,
  'containsModule' AS predicate,
  UNNEST(json_keys(json_extract(spec, '$.modules'))) AS object
FROM notebook_specs;

-- notebook → repoLocation → file path
-- Use glob() to enumerate actually-existing notebook HTML files,
-- then derive the notebook id from the filename.
CREATE OR REPLACE VIEW kb_repo_location AS
SELECT
  regexp_replace(regexp_replace(file, '^.*/', ''), '\.html$', '') AS subject,
  'repoLocation' AS predicate,
  file AS object
FROM glob(['lopecode/notebooks/*.html', 'lopebooks/notebooks/*.html']);

-- notebook → globalFile → filename
-- File attachments declared at the spec's top level with no module owner
-- (e.g. shared CSS like syntax.css). Module-scoped attachments are surfaced
-- separately via kb_module_file, mirroring the spec's two-level shape.
CREATE OR REPLACE VIEW kb_global_file AS
WITH files AS (
  SELECT
    json_extract_string(spec, '$.notebook') AS notebook,
    UNNEST(from_json(json_extract(spec, '$.files'), '["VARCHAR"]')) AS file
  FROM notebook_specs
  WHERE json_extract(spec, '$.files') IS NOT NULL
)
SELECT DISTINCT notebook AS subject, 'globalFile' AS predicate, file AS object
FROM files;

-- (notebook::module) → moduleFile → filename
-- File attachments owned by a specific module — gzipped vendored libs,
-- per-module JSON state, images, etc. Composite subject mirrors
-- dependsOn/dependedBy: the same module may bundle different attachments in
-- different notebooks. Filenames are bare (no module prefix), matching the
-- spec's `modules.<slug>.files` array; the on-disk <script> id is
-- conventionally `<slug>/<filename>`.
CREATE OR REPLACE VIEW kb_module_file AS
WITH per_module AS (
  SELECT
    json_extract_string(spec, '$.notebook') AS notebook,
    UNNEST(json_keys(json_extract(spec, '$.modules'))) AS module,
    spec
  FROM notebook_specs
), edges AS (
  SELECT
    notebook || '::' || module AS subject,
    UNNEST(from_json(json_extract(spec, '$.modules."' || module || '".files'), '["VARCHAR"]')) AS object
  FROM per_module
  WHERE json_extract(spec, '$.modules."' || module || '".files') IS NOT NULL
)
SELECT DISTINCT subject, 'moduleFile' AS predicate, object FROM edges;

-- (notebook::module) → dependsOn → imported_module
-- Subject is the composite form because dependencies are per-(notebook, module):
-- two notebooks may bundle different versions of the same module with different
-- dependency sets. Mirrors @tomlarkworthy/module-map's per-runtime view.
CREATE OR REPLACE VIEW kb_depends_on AS
WITH per_module AS (
  SELECT
    json_extract_string(spec, '$.notebook') AS notebook,
    UNNEST(json_keys(json_extract(spec, '$.modules'))) AS module,
    spec
  FROM notebook_specs
), edges AS (
  SELECT
    notebook || '::' || module AS subject,
    UNNEST(from_json(json_extract(spec, '$.modules."' || module || '".dependsOn'), '["VARCHAR"]')) AS object
  FROM per_module
  WHERE json_extract(spec, '$.modules."' || module || '".dependsOn') IS NOT NULL
)
SELECT DISTINCT subject, 'dependsOn' AS predicate, object FROM edges;

-- (notebook::module) → dependedBy → dependent_module
-- Reverse edge of dependsOn, scoped to modules within the same notebook
-- (lope-reader.ts only emits dependedBy for modules that exist in the spec).
CREATE OR REPLACE VIEW kb_depended_by AS
WITH per_module AS (
  SELECT
    json_extract_string(spec, '$.notebook') AS notebook,
    UNNEST(json_keys(json_extract(spec, '$.modules'))) AS module,
    spec
  FROM notebook_specs
), edges AS (
  SELECT
    notebook || '::' || module AS subject,
    UNNEST(from_json(json_extract(spec, '$.modules."' || module || '".dependedBy'), '["VARCHAR"]')) AS object
  FROM per_module
  WHERE json_extract(spec, '$.modules."' || module || '".dependedBy') IS NOT NULL
)
SELECT DISTINCT subject, 'dependedBy' AS predicate, object FROM edges;

-- notebook → upstream → module
-- A module that this notebook bundles as a primary authored source (rather
-- than a transitive dep). Derived from the per-notebook spec's `upstreams`
-- map, which is keyed by host then module. We currently only surface the
-- `observablehq.com` host, but the view is shaped so additional hosts could
-- be unioned in without changing the predicate.
--
-- For multi-source bundles (e.g. atproto, jumpgates) this yields one triple
-- per source. For single-source notebooks it yields exactly one triple.
--
-- Two on-disk shapes exist and are normalized here:
--   * new schema: { "upstreams": { "observablehq.com": { "@a/b": "<url>" } } }
--   * legacy:     { "observablehq.com": "<url>" }                  (single-source only)
-- Legacy entries derive the module slug by stripping the host prefix from the URL.
CREATE OR REPLACE VIEW kb_upstream AS
WITH new_form AS (
  SELECT
    json_extract_string(spec, '$.notebook') AS notebook,
    UNNEST(json_keys(json_extract(spec, '$.upstreams."observablehq.com"'))) AS module
  FROM notebook_specs
  WHERE json_extract(spec, '$.upstreams."observablehq.com"') IS NOT NULL
), legacy_form AS (
  SELECT
    json_extract_string(spec, '$.notebook') AS notebook,
    regexp_replace(
      json_extract_string(spec, '$."observablehq.com"'),
      '^https://observablehq\.com/', ''
    ) AS module
  FROM notebook_specs
  WHERE json_extract(spec, '$."observablehq.com"') IS NOT NULL
    AND json_extract(spec, '$.upstreams') IS NULL
)
SELECT DISTINCT notebook AS subject, 'upstream' AS predicate, module AS object
FROM (SELECT * FROM new_form UNION ALL SELECT * FROM legacy_form);

-- ---------- Unified triple view (the main query surface) ----------

CREATE OR REPLACE VIEW kb_triples AS
  SELECT * FROM kb_observable_url
  UNION ALL SELECT * FROM kb_published_at
  UNION ALL SELECT * FROM kb_contains_module
  UNION ALL SELECT * FROM kb_repo_location
  UNION ALL SELECT * FROM kb_global_file
  UNION ALL SELECT * FROM kb_module_file
  UNION ALL SELECT * FROM kb_depends_on
  UNION ALL SELECT * FROM kb_depended_by
  UNION ALL SELECT * FROM kb_upstream;
