-- ============================================================
-- kb/views.sql — DuckDB views over lopecode-dev's committed JSON
-- ============================================================
-- Run from the lopecode-dev repo root:
--   duckdb -init kb/views.sql -c "SELECT * FROM kb_triples LIMIT 10"
--
-- See knowledge/querying-and-maintaining-the-lopecode-structured-knowledgebase.md
-- for the predicate vocabulary, design rationale, and maintenance notes.
--
-- Source files (all tracked in git):
--   content.json                                   — module catalogue (observableUrl, publishedAt)
--   {lopecode,lopebooks}/notebooks/@*.json         — per-notebook specs (regenerated by jumpgate via lope-reader.ts)
-- ============================================================

-- ---------- Source views (1:1 with the JSON files) ----------

-- content.json structure: { version, categories: [...], entries: [...] }
-- Each entry has: slug, url, title, description, sourceUrl, category, ...
CREATE OR REPLACE VIEW catalogue AS
SELECT entry.* FROM (
  SELECT UNNEST(entries) AS entry
  FROM read_json_auto('content.json', maximum_object_size=104857600)
);

-- Per-notebook spec files. Each file is one JSON object:
--   { notebook, title, bootconf, files, modules: { "<slug>": {hash, files?}, ... } }
-- read_json_objects keeps each file as a single JSON value, which avoids the
-- schema-union explosion that read_json_auto would produce across heterogeneous
-- notebooks (different module key sets).
CREATE OR REPLACE VIEW notebook_specs AS
SELECT json::JSON AS spec FROM read_json_objects(
  ['lopecode/notebooks/@*.json', 'lopebooks/notebooks/@*.json']
);

-- ---------- Triple-shaped views (one per predicate) ----------

-- module → observableUrl → URL
CREATE OR REPLACE VIEW kb_observable_url AS
SELECT slug AS subject, 'observableUrl' AS predicate, sourceUrl AS object
FROM catalogue
WHERE sourceUrl IS NOT NULL;

-- module → publishedAt → URL  (GitHub Pages location)
CREATE OR REPLACE VIEW kb_published_at AS
SELECT slug AS subject, 'publishedAt' AS predicate, url AS object
FROM catalogue
WHERE url IS NOT NULL;

-- notebook → containsModule → module
-- Derived from the per-notebook spec's `modules` object — its keys are exactly
-- the modules bundled into that notebook. Deduplicated because the same
-- notebook id may appear in both lopecode/ and lopebooks/.
CREATE OR REPLACE VIEW kb_contains_module AS
SELECT DISTINCT
  json_extract_string(spec, '$.notebook') AS subject,
  'containsModule' AS predicate,
  UNNEST(json_keys(json_extract(spec, '$.modules'))) AS object
FROM notebook_specs;

-- notebook → repoLocation → file path
-- Use glob() to enumerate actually-existing notebook HTML files,
-- then derive the notebook id from the filename.
CREATE OR REPLACE VIEW kb_repo_location AS
SELECT
  regexp_replace(regexp_replace(file, '^.*/', ''), '\.html$', '') AS subject,
  'repoLocation' AS predicate,
  file AS object
FROM glob(['lopecode/notebooks/*.html', 'lopebooks/notebooks/*.html']);

-- ---------- Unified triple view (the main query surface) ----------

CREATE OR REPLACE VIEW kb_triples AS
  SELECT * FROM kb_observable_url
  UNION ALL SELECT * FROM kb_published_at
  UNION ALL SELECT * FROM kb_contains_module
  UNION ALL SELECT * FROM kb_repo_location;
