// Emits inject.js — a plain script the page fetches and evals, which puts editor-5 on
// instantiateDataflow. Written as real JS rather than Observable source so nothing has to be
// compiled in the page, and so the 13KB never travels through an MCP tool call.
//
// Defining a name that already exists creates a DUPLICATE variable and collapses both into an
// error, so existing names are located and re-defined in place.
import { readFileSync, writeFileSync } from "node:fs";

const here = (p) => new URL(p, import.meta.url).pathname;
const REPO = "/Users/tom.larkworthy/dev/lopecode-dev/";

const impl = readFileSync(here("./instantiate-dataflow.mjs"), "utf8")
  .replace(/^export default [^\n]*\n/gm, "")
  .replace(/^export /gm, "")
  .trim();

const mod = readFileSync(REPO + "modules/@tomlarkworthy/editor-5.js", "utf8");
const m = mod.match(/const _\w+ = function _cellEditor\(([^)]*)\)\{return\(\n([\s\S]*?)\n\)\};/);
if (!m) throw new Error("cellEditor not found");
const deps = m[1].split(",").map((s) => s.trim());
const body = m[2];
if (!deps.includes("cloneDataflow")) throw new Error("cloneDataflow not a dependency of cellEditor");
const newDeps = deps.map((d) => (d === "cloneDataflow" ? "cloneViaSandbox" : d));
const newBody = body.replace(/\bcloneDataflow\b/g, "cloneViaSandbox");

const script = `// generated by tools/dataflow-templating-2/make-inject.mjs — do not edit
(() => {
${impl}

const rt = window.__ojs_runtime;
if (!rt) return { error: "no runtime" };

const seed = [...rt._variables].find((v) => v._name === "cellEditor" && v._definition);
if (!seed) return { error: "cellEditor not found in runtime" };
const ed = seed._module;

const existing = (name) =>
  [...rt._variables].find((v) => v._module === ed && v._name === name);

// Re-define in place when the name is taken; a fresh .define() on a taken name makes a duplicate.
const put = (name, inputs, definition) => {
  const v = existing(name);
  if (v) { v.define(name, inputs, definition); return "redefined"; }
  ed.variable().define(name, inputs, definition);
  return "defined";
};

const report = {};
report.instantiateDataflowFactory = put("instantiateDataflowFactory", [], () => instantiateDataflowFactory);
report.instantiateDataflow = put("instantiateDataflow", ["instantiateDataflowFactory", "runtime"],
  (factory, runtime) => factory(runtime.constructor, {}));
report.cloneViaSandbox = put("cloneViaSandbox", ["instantiateDataflow", "onCodeChange"],
  (instantiateDataflow, onCodeChange) => (variables, observerFactory = () => ({})) => {
    const inst = instantiateDataflow(variables, { observers: observerFactory, watch: onCodeChange });
    return () => inst.dispose();
  });
// Same shape the compiled module uses: a function of the dependency list returning the cell value.
report.cellEditor = put("cellEditor", ${JSON.stringify(newDeps)},
  function (${newDeps.join(", ")}) { return (
${newBody}
); });

window.__v2 = { deps: ${JSON.stringify(newDeps)} };
return report;
})()
`;

writeFileSync(here("./inject.js"), script);
console.log(`inject.js written, cellEditor deps: ${newDeps.join(", ")}`);
