#!/usr/bin/env bun
/**
 * lope-depmap.ts - Build a dependency map from notebook specs
 *
 * For each module, lists which notebooks contain it.
 * Reads .json specs generated by lope-reader.ts.
 *
 * Usage:
 *   bun tools/lope-depmap.ts [dir...]    # defaults to lopecode/notebooks lopebooks/notebooks
 */

import { readFileSync } from "fs";

const dirs = process.argv.length > 2
  ? process.argv.slice(2)
  : ["lopecode/notebooks", "lopebooks/notebooks"];

interface NotebookSpec {
  notebook: string;
  title: string;
  modules: Record<string, unknown>;
}

// module -> set of notebook names
const depmap = new Map<string, Set<string>>();

for (const dir of dirs) {
  const glob = new Bun.Glob("*.json");
  for (const file of glob.scanSync({ cwd: dir, absolute: true })) {
    try {
      const spec: NotebookSpec = JSON.parse(readFileSync(file, "utf-8"));
      if (!spec.modules) continue;
      for (const mod of Object.keys(spec.modules)) {
        if (!depmap.has(mod)) depmap.set(mod, new Set());
        depmap.get(mod)!.add(spec.notebook);
      }
    } catch {
      continue;
    }
  }
}

// Sort by number of dependents (most used first)
const sorted = [...depmap.entries()].sort((a, b) => b[1].size - a[1].size);

const output: Record<string, string[]> = {};
for (const [mod, notebooks] of sorted) {
  output[mod] = [...notebooks].sort();
}

console.log(JSON.stringify(output, null, 2));
