#!/usr/bin/env bun
/**
 * lope-depmap.ts - Build a dependency map and detect stale notebooks
 *
 * For each module, lists which notebooks contain it and whether they're in sync.
 * Reads .json specs generated by lope-reader.ts (which include content hashes).
 * The most common hash is treated as canonical; the most recently modified file
 * with that hash is reported as the source.
 *
 * Usage:
 *   bun tools/lope-depmap.ts [dir...]          # full depmap (default dirs)
 *   bun tools/lope-depmap.ts --stale [dir...]  # only show out-of-sync modules
 *   bun tools/lope-depmap.ts --sync  [dir...]  # output sync-module commands
 */

import { readFileSync, statSync } from "fs";
import { resolve } from "path";

const args = process.argv.slice(2);
const staleOnly = args.includes("--stale");
const syncMode = args.includes("--sync");
const dirs = args.filter((a) => !a.startsWith("--"));
if (dirs.length === 0) dirs.push("lopecode/notebooks", "lopebooks/notebooks");

interface NotebookSpec {
  notebook: string;
  title: string;
  modules: Record<string, { hash: string; files?: string[] }>;
}

interface ModuleEntry {
  notebook: string;
  htmlPath: string;
  hash: string;
  mtime: number;
}

// module -> list of entries
const depmap = new Map<string, ModuleEntry[]>();

for (const dir of dirs) {
  const absDir = resolve(dir);
  const glob = new Bun.Glob("*.json");
  for (const file of glob.scanSync({ cwd: absDir, absolute: true })) {
    try {
      const spec: NotebookSpec = JSON.parse(readFileSync(file, "utf-8"));
      if (!spec.modules) continue;

      const htmlPath = file.replace(/\.json$/, ".html");
      let mtime = 0;
      try {
        mtime = statSync(htmlPath).mtimeMs;
      } catch {}

      for (const [mod, info] of Object.entries(spec.modules)) {
        if (!depmap.has(mod)) depmap.set(mod, []);
        depmap.get(mod)!.push({
          notebook: spec.notebook,
          htmlPath,
          hash: info.hash,
          mtime,
        });
      }
    } catch {
      continue;
    }
  }
}

function findStaleModules() {
  const stale: Record<string, { latest: string; source: string; behind: string[] }> = {};

  for (const [mod, entries] of depmap) {
    const hashCounts = new Map<string, number>();
    for (const e of entries) {
      hashCounts.set(e.hash, (hashCounts.get(e.hash) || 0) + 1);
    }
    if (hashCounts.size <= 1) continue; // all in sync

    // Most common hash is canonical
    const latestHash = [...hashCounts.entries()].sort((a, b) => b[1] - a[1])[0][0];

    // Source = most recently modified file with the canonical hash
    const source = entries
      .filter((e) => e.hash === latestHash)
      .reduce((a, b) => (a.mtime > b.mtime ? a : b));

    const behind = entries
      .filter((e) => e.hash !== latestHash)
      .map((e) => e.htmlPath);

    stale[mod] = { latest: latestHash, source: source.htmlPath, behind };
  }

  return stale;
}

if (staleOnly || syncMode) {
  const stale = findStaleModules();
  if (Object.keys(stale).length === 0) {
    console.log("All notebooks are in sync.");
  } else if (syncMode) {
    // Output sync-module commands
    const sorted = Object.entries(stale).sort((a, b) => b[1].behind.length - a[1].behind.length);
    for (const [mod, info] of sorted) {
      for (const target of info.behind) {
        console.log(`bun tools/channel/sync-module.ts --module "${mod}" --source "${info.source}" --target "${target}"`);
      }
    }
  } else {
    const sorted = Object.fromEntries(
      Object.entries(stale).sort((a, b) => b[1].behind.length - a[1].behind.length)
    );
    console.log(JSON.stringify(sorted, null, 2));
  }
} else {
  const sorted = [...depmap.entries()].sort((a, b) => b[1].length - a[1].length);

  const output: Record<string, { notebooks: string[]; inSync: boolean }> = {};
  for (const [mod, entries] of sorted) {
    const hashes = new Set(entries.map((e) => e.hash));
    output[mod] = {
      notebooks: entries.map((e) => e.htmlPath).sort(),
      inSync: hashes.size <= 1,
    };
  }

  console.log(JSON.stringify(output, null, 2));
}
